name: black

on: [push]

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - name: Black Code Formatter
      #   uses: wrboyce/python-lint-action@master
      - name: Black Code Checker
        uses: tdeboissiere/python-format-action@master
        with:
          args: ". "
